version: '3.8'

services:
  streamlit:
    build: .
    container_name: patents_streamlit
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=patents
      - DB_USER=patuser
      - DB_PASS=secret123
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: patents_postgres
    environment:
      POSTGRES_DB: patents
      POSTGRES_USER: patuser
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata:
